package exception;

public class MultipleCatchBlock {

	public static void main(String[] args) {
		int a=10,b=2;
		int []arr=new int[5];
		String str=null;
		try {
			System.out.println(a/b);
			 arr[4]=30/5;
			 System.out.println(arr[4]);
			 System.out.println(str.length());
			 
		}catch(ArithmeticException e)
		{
			System.out.println(e.getMessage());
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println(e.getMessage());
		}
		catch(NullPointerException e)
		{
			System.out.println(e.getMessage());
		}
	}

}
